apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy #>Charts.name
  labels:
    app: frontend #charts.createuserlabels
spec:
  replicas: 1 #.values.replicaCount
  selector:
    matchLabels:
      app: frontend #Charts.createuserlables
  template:
    metadata:
      labels:
        app: frontend #Charts.createuserlables
    spec:
      containers:
        - name: pyapp #.Chart.Name
          image: adesh0303/flaskapp:frontend-UI #.Values.image.repository:.Values.images.tag
