apiVersion: v1
kind: PersistentVolume
metadata:
  name: MYAPP
  namespace: default
  labels:
    app: MYAPP
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi