apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-app
  labels:
    app: deleteuser
    config: appspecs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deleteuser
      config: appspecs
  template:
    metadata:
      labels:
        app: deleteuser
        config: appspecs
    spec:
      containers:
        - name: deleteuser
          image: adesh0303/eks-app:deleteuser-base
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: dbhost
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: dbpass
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: dbuser
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: dbport
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pyapp-config
                  key: dbname
