apiVersion: apps/v1
kind: Deployment
metadata:
  name: createuser-app
  labels:
    app: createuser
    config: appspecs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: createuser
      config: appspecs
  template:
    metadata:
      labels:
        app: createuser
    spec:
      containers:
        - name: createuser
          image: adesh0303/eks-app:createuserservice
          envFrom:
            - configMapRef:
                name: pyapp-config
      restartPolicy: Never
